// Auto-generated by memo-grafter init.
// Do not edit this file manually. Re-run `npx memo-grafter init` to regenerate it.

export const memoGrafterExtensions = [
  {
    "name": "vector",
    "description": "pgvector support for topic and memory embeddings."
  },
  {
    "name": "pgcrypto",
    "description": "UUID generation for MemoGrafter memory and registry rows."
  }
] as const;

export const memoGrafterTables = {
  mg_message_buffer: {
    name: "mg_message_buffer",
    description: "Ordered raw messages for each MemoGrafter session.",
    columns: {
      session_id: {
        name: "session_id",
        type: "text",
        primaryKey: true,
      },
      message_index: {
        name: "message_index",
        type: "int",
        primaryKey: true,
      },
      role: {
        name: "role",
        type: "text",
      },
      content: {
        name: "content",
        type: "text",
      },
    }
  },
  mg_segments: {
    name: "mg_segments",
    description: "Topic segment ranges detected during ingestion.",
    columns: {
      id: {
        name: "id",
        type: "text",
        primaryKey: true,
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      start_index: {
        name: "start_index",
        type: "int",
      },
      end_index: {
        name: "end_index",
        type: "int",
      },
      topic_order: {
        name: "topic_order",
        type: "int",
      },
      drift_score: {
        name: "drift_score",
        type: "float",
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["UNIQUE (session_id, start_index, end_index)"]
  },
  mg_topic_nodes: {
    name: "mg_topic_nodes",
    description: "Topic-level graph nodes with summaries and embeddings.",
    columns: {
      id: {
        name: "id",
        type: "text",
        primaryKey: true,
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      segment_id: {
        name: "segment_id",
        type: "text",
        references: "mg_segments(id)",
      },
      label: {
        name: "label",
        type: "text",
        nullable: true,
      },
      summary: {
        name: "summary",
        type: "text",
        nullable: true,
      },
      embedding: {
        name: "embedding",
        type: "vector",
        nullable: true,
      },
      tags: {
        name: "tags",
        type: "text[]",
        default: "'{}'",
      },
      source: {
        name: "source",
        type: "text",
        nullable: true,
      },
      message_range: {
        name: "message_range",
        type: "int",
        nullable: true,
      },
      topic_order: {
        name: "topic_order",
        type: "int",
        default: "0",
      },
      drift_score: {
        name: "drift_score",
        type: "float",
        default: "0",
      },
      agent_color: {
        name: "agent_color",
        type: "text",
        nullable: true,
      },
      fleet_id: {
        name: "fleet_id",
        type: "text",
        nullable: true,
      },
      agent_id: {
        name: "agent_id",
        type: "text",
        nullable: true,
      },
      suppressed: {
        name: "suppressed",
        type: "boolean",
        default: "false",
      },
      suppressed_at: {
        name: "suppressed_at",
        type: "timestamptz",
        nullable: true,
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["UNIQUE (segment_id)"]
  },
  mg_topic_edges: {
    name: "mg_topic_edges",
    description: "Temporal, semantic, reentry, and graft edges between topic nodes.",
    columns: {
      src_id: {
        name: "src_id",
        type: "text",
        primaryKey: true,
      },
      dst_id: {
        name: "dst_id",
        type: "text",
        primaryKey: true,
      },
      weight: {
        name: "weight",
        type: "float",
      },
      type: {
        name: "type",
        type: "text",
      },
    }
  },
  mg_memory_nodes: {
    name: "mg_memory_nodes",
    description: "Structured memory facts extracted from topic segments.",
    columns: {
      id: {
        name: "id",
        type: "uuid",
        primaryKey: true,
        default: "gen_random_uuid()",
      },
      segment_id: {
        name: "segment_id",
        type: "text",
        references: "mg_segments(id)",
      },
      topic_node_id: {
        name: "topic_node_id",
        type: "text",
        references: "mg_topic_nodes(id)",
      },
      agent_id: {
        name: "agent_id",
        type: "text",
        nullable: true,
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      memory_type: {
        name: "memory_type",
        type: "text",
        check: "fact|insight|question|task|reference",
      },
      source_type: {
        name: "source_type",
        type: "text",
        default: "conversation",
        check: "conversation|note|document|code",
      },
      subject: {
        name: "subject",
        type: "text",
      },
      predicate: {
        name: "predicate",
        type: "text",
      },
      value: {
        name: "value",
        type: "text",
      },
      confidence: {
        name: "confidence",
        type: "float",
        default: "1.0",
      },
      embedding: {
        name: "embedding",
        type: "vector",
        nullable: true,
      },
      tags: {
        name: "tags",
        type: "text[]",
        default: "'{}'",
      },
      source: {
        name: "source",
        type: "text",
        nullable: true,
      },
      source_url: {
        name: "source_url",
        type: "text",
        nullable: true,
      },
      source_title: {
        name: "source_title",
        type: "text",
        nullable: true,
      },
      superseded_by: {
        name: "superseded_by",
        type: "uuid",
        nullable: true,
        references: "mg_memory_nodes(id)",
      },
      decayed: {
        name: "decayed",
        type: "boolean",
        default: "false",
      },
      forgotten: {
        name: "forgotten",
        type: "boolean",
        default: "false",
      },
      forgotten_at: {
        name: "forgotten_at",
        type: "timestamptz",
        nullable: true,
      },
      has_conflict: {
        name: "has_conflict",
        type: "boolean",
        default: "false",
      },
      agent_color: {
        name: "agent_color",
        type: "text",
        nullable: true,
      },
      fleet_id: {
        name: "fleet_id",
        type: "text",
        nullable: true,
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    }
  },
  mg_memory_edges: {
    name: "mg_memory_edges",
    description: "Semantic, conflict, update, and related edges between memory facts.",
    columns: {
      id: {
        name: "id",
        type: "uuid",
        primaryKey: true,
        default: "gen_random_uuid()",
      },
      source_id: {
        name: "source_id",
        type: "uuid",
        references: "mg_memory_nodes(id)",
      },
      target_id: {
        name: "target_id",
        type: "uuid",
        references: "mg_memory_nodes(id)",
      },
      edge_type: {
        name: "edge_type",
        type: "text",
        check: "semantic|conflicts|updates|related",
      },
      weight: {
        name: "weight",
        type: "float",
        nullable: true,
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    }
  },
  mg_fleets: {
    name: "mg_fleets",
    description: "Fleet metadata for multi-agent memory groups.",
    columns: {
      id: {
        name: "id",
        type: "text",
        primaryKey: true,
      },
      name: {
        name: "name",
        type: "text",
        nullable: true,
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    }
  },
  mg_fleet_agents: {
    name: "mg_fleet_agents",
    description: "Registered worker agents within fleets.",
    columns: {
      id: {
        name: "id",
        type: "text",
        primaryKey: true,
      },
      fleet_id: {
        name: "fleet_id",
        type: "text",
        references: "mg_fleets(id)",
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      agent_color: {
        name: "agent_color",
        type: "text",
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["UNIQUE (fleet_id, agent_color)"]
  },
  mg_sessions: {
    name: "mg_sessions",
    description: "Human-friendly metadata for MemoGrafter sessions.",
    columns: {
      session_id: {
        name: "session_id",
        type: "text",
        primaryKey: true,
      },
      label: {
        name: "label",
        type: "text",
        nullable: true,
      },
      description: {
        name: "description",
        type: "text",
        nullable: true,
      },
      tags: {
        name: "tags",
        type: "text[]",
        default: "'{}'",
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
      updated_at: {
        name: "updated_at",
        type: "timestamptz",
        default: "now()",
      },
    }
  },
  mg_session_ingest_state: {
    name: "mg_session_ingest_state",
    description: "Incremental ingestion checkpoints by session.",
    columns: {
      session_id: {
        name: "session_id",
        type: "text",
        primaryKey: true,
      },
      last_ingested_message_index: {
        name: "last_ingested_message_index",
        type: "int",
        default: "-1",
      },
      updated_at: {
        name: "updated_at",
        type: "timestamptz",
        default: "now()",
      },
    }
  },
  mg_graft_registry: {
    name: "mg_graft_registry",
    description: "Tracks copied/grafted topic node origins.",
    columns: {
      id: {
        name: "id",
        type: "uuid",
        primaryKey: true,
        default: "gen_random_uuid()",
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      node_id: {
        name: "node_id",
        type: "text",
        references: "mg_topic_nodes(id)",
      },
      source_session_id: {
        name: "source_session_id",
        type: "text",
      },
      source_node_id: {
        name: "source_node_id",
        type: "text",
      },
      grafted_at: {
        name: "grafted_at",
        type: "timestamptz",
        default: "now()",
      },
    }
  },
} as const;

export const memoGrafterIndexes = [
  {
    "name": "mg_message_buffer_session_idx",
    "table": "mg_message_buffer",
    "description": "Message lookup by session and index."
  },
  {
    "name": "mg_segments_session_idx",
    "table": "mg_segments",
    "description": "Segment lookup by session and topic order."
  },
  {
    "name": "mg_nodes_session_idx",
    "table": "mg_topic_nodes",
    "description": "Topic lookup by session and topic order."
  },
  {
    "name": "idx_topic_nodes_active_lifecycle",
    "table": "mg_topic_nodes",
    "description": "Active topic lifecycle lookup."
  },
  {
    "name": "mg_topic_nodes_tags_idx",
    "table": "mg_topic_nodes",
    "description": "Topic tag lookup."
  },
  {
    "name": "mg_nodes_fleet_idx",
    "table": "mg_topic_nodes",
    "description": "Fleet topic lookup by color."
  },
  {
    "name": "mg_fleet_agents_fleet_idx",
    "table": "mg_fleet_agents",
    "description": "Fleet agent lookup by color."
  },
  {
    "name": "mg_sessions_label_lower_idx",
    "table": "mg_sessions",
    "description": "Case-insensitive session label lookup."
  },
  {
    "name": "mg_session_ingest_state_updated_idx",
    "table": "mg_session_ingest_state",
    "description": "Ingest state freshness lookup."
  },
  {
    "name": "idx_graft_registry_session",
    "table": "mg_graft_registry",
    "description": "Graft registry lookup by session."
  },
  {
    "name": "idx_graft_registry_node_unique",
    "table": "mg_graft_registry",
    "description": "Unique graft registry node ownership."
  },
  {
    "name": "idx_graft_registry_source_target_unique",
    "table": "mg_graft_registry",
    "description": "Prevents duplicate source-topic grafts into a target session."
  },
  {
    "name": "idx_graft_registry_source",
    "table": "mg_graft_registry",
    "description": "Source topic provenance lookup."
  },
  {
    "name": "mg_nodes_embedding_idx",
    "table": "mg_topic_nodes",
    "description": "Topic vector similarity search."
  },
  {
    "name": "idx_memory_nodes_topic",
    "table": "mg_memory_nodes",
    "description": "Memory lookup by topic node."
  },
  {
    "name": "idx_memory_nodes_segment",
    "table": "mg_memory_nodes",
    "description": "Memory lookup by segment."
  },
  {
    "name": "idx_memory_nodes_session",
    "table": "mg_memory_nodes",
    "description": "Memory lookup by session."
  },
  {
    "name": "idx_memory_nodes_active_lifecycle",
    "table": "mg_memory_nodes",
    "description": "Active memory lifecycle lookup."
  },
  {
    "name": "idx_memory_nodes_tags",
    "table": "mg_memory_nodes",
    "description": "Memory tag lookup."
  },
  {
    "name": "idx_memory_nodes_embedding",
    "table": "mg_memory_nodes",
    "description": "Memory vector similarity search."
  },
  {
    "name": "idx_memory_edges_source",
    "table": "mg_memory_edges",
    "description": "Memory edge lookup by source."
  },
  {
    "name": "idx_memory_edges_target",
    "table": "mg_memory_edges",
    "description": "Memory edge lookup by target."
  }
] as const;
