import type { Message } from "../core/types.js";
import { normalizeText } from "../utils/text/normalizeText.js";

export function buildSegmentExtractionPrompt(messages: Message[], labelHint?: string, sourceType: "conversation" | "note" | "document" | "code" = "conversation"): string {
  const documentMode = sourceType !== "conversation";
  const messageContent = messages
    .map((message, index) => `Message ${index + 1}:\n[${message.role}] ${normalizeText(message.content) ?? message.content}`)
    .join("\n\n");

  return [
    documentMode ? "Analyze this document segment and extract only durable, reusable knowledge for a future chatbot." : "Analyze this conversation segment and extract only durable user memory for a future chatbot.",
    "",
    "Return a single valid JSON object and nothing else. Do not include markdown fences, backticks, a preamble, comments, or trailing text.",
    "",
    "The JSON object must match this exact schema:",
    "{",
    '  "label": "3-6 word topic label",',
    '  "user_intent": "two-three sentences describing what the user was trying to achieve",',
    '  "outcome": "one-two sentences describing what was concluded, decided, or provided",',
    '  "open": "one sentence describing any unresolved question, or null",',
    '  "memories": [',
    "    {",
    '      "memory_type": "fact | insight | question | task | reference",',
    '      "subject": "person, team, project, system, tool, or concept the memory is about",',
    '      "predicate": "short relationship or attribute phrase",',
    '      "value": "one sentence maximum, self-contained and meaningful without surrounding context",',
    '      "confidence": 0.95,',
    '      "provenance": {',
    `        "speaker": "${documentMode ? "document" : "user"}",`,
    '        "message_indexes": [1],',
    `        "extraction_method": "${documentMode ? "document-extraction" : "explicit | inferred | user-confirmed"}"`,
    "      }",
    "    }",
    "  ]",
    "}",
    "",
    "Memory type definitions:",
    "- fact: explicit assertion, preference, decision, or constraint directly stated",
    "- insight: synthesized or implied understanding, not directly stated",
    "- question: an important unresolved user goal whose future resolution matters",
    "- task: something actionable, a to-do, or next step",
    "- reference: an external tool, service, library, or resource being discussed",
    "",
    "Confidence scoring:",
    "- Explicit direct statement: 0.9-1.0",
    "- Implied or inferred: 0.5-0.8",
    "- Uncertain or speculative: below 0.5",
    "",
    "Rules:",
    "- Return only memories likely to remain useful beyond this exchange.",
    ...(documentMode ? [
      "- Attribute every memory to document with extraction_method document-extraction.",
      "- message_indexes are the one-based Message numbers that directly support the memory.",
    ] : [
      "- Only user-authored or explicitly user-confirmed information may become durable memory.",
      "- Never turn an assistant suggestion, assistant question, generated explanation, recipe, code, example, or acknowledgement into a user fact.",
      "- A user asking a one-off question is not by itself a durable preference or fact.",
      "- Store an assistant-introduced idea only when a later user message clearly accepts, saves, chooses, or confirms it; use user-confirmed.",
      "- speaker must be user, and every message_indexes entry must point to a supporting [user] message.",
    ]),
    "- The value field must be one sentence maximum.",
    "- The value field must be self-contained and meaningful without surrounding context.",
    "- When a statement explicitly corrects, replaces, or updates an earlier fact, preserve that update cue in the value, such as actually, now, changed to, or instead.",
    "- If no memories are extractable from the segment, return an empty memories array.",
    "- Use null for open when there is no unresolved question or follow-up.",
    ...(labelHint
      ? [
        `- Use "${labelHint}" as a hint when choosing the topic label. Keep the label accurate to the content.`,
      ]
      : []),
    "",
    "Example segment:",
    "Message 1:",
    "[user] I prefer PostgreSQL over MongoDB for this billing service because we need relational integrity. Should connection pooling live in the app or infra layer?",
    "",
    "Message 2:",
    "[assistant] PostgreSQL is a good fit for the billing service. Connection pooling can work in either place; the team should decide based on deployment ownership.",
    "",
    "Expected JSON output:",
    "{",
    '  "label": "Billing Database Choice",',
    '  "user_intent": "The user wanted to confirm a database preference for a billing service and clarify where connection pooling should be handled. They emphasized the need for relational integrity.",',
    '  "outcome": "PostgreSQL was treated as a good fit for the billing service. The connection pooling decision was left dependent on deployment ownership.",',
    '  "open": "The team still needs to decide whether connection pooling belongs in the app or infra layer.",',
    '  "memories": [',
    "    {",
    '      "memory_type": "fact",',
    '      "subject": "user",',
    '      "predicate": "prefers database",',
    '      "value": "PostgreSQL over MongoDB for the billing service because it needs relational integrity.",',
    '      "confidence": 0.95,',
    '      "provenance": { "speaker": "user", "message_indexes": [1], "extraction_method": "explicit" }',
    "    },",
    "    {",
    '      "memory_type": "question",',
    '      "subject": "team",',
    '      "predicate": "undecided on",',
    '      "value": "whether connection pooling should live in the app or infra layer.",',
    '      "confidence": 0.8,',
    '      "provenance": { "speaker": "user", "message_indexes": [1], "extraction_method": "explicit" }',
    "    }",
    "  ]",
    "}",
    "",
    "Conversation segment:",
    messageContent,
  ].join("\n");
}
